# Generated by Django 5.1.7 on 2025-04-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='emails',
            new_name='email',
        ),
    ]
